### ISSUE TITLE
Compile on Debian Wheezy and Varnish 4.0.2 fails

### ISSUE THREAD

**Issue by razvanphp** [varnish/libvmod-header#12]
Hi,

I tried to compile the 4.0 and master branch today but both fail every time.

````
checking for /tmp/varnish-4.0.2/include/varnishapi.h... no
configure: error: in `/home/vagrant/libvmod-header':
configure: error: "/tmp/varnish-4.0.2" is not a Varnish source directory
````

Also I had to download the tar.gz source, did not work with the dist dev package (I compiled other vmods without the need of varnish source)

**Comment by aondio** [comment]
@razvanphp 
Hi, it seems like you're using the branch 3.0 of the vmod, instead of 4.0.

**Comment by razvanphp** [comment]
You are right, stupid me, sorry.
